// Generated by CoffeeScript 1.8.0
(function() {
  $(".swiper-container").slick({
    dots: true,
    speed: 500,
    arrows: true,
    prevArrow: $("#home-page-quote-left"),
    nextArrow: $("#home-page-quote-right")
  });

}).call(this);

//# sourceMappingURL=script.js.map
